### ISSUE TITLE
Can't find module

### ISSUE THREAD

**Issue by DoYouKnowTheAnswer** [watermarkchurch/contentful-schema-diff#132] opened 2021-02-15 23:42 UTC
Steps to reproduce:
1. Be sure you are running node v14.15.4
2. install contentful-schema-diff
3.  run: $ contentful-schema-diff --from <from space> --to <to space> --token <my contentful management token>

Expected: migration scripts are created

Actual:
_http_agent.js:444
      options = req[kRequestOptions];
                   ^

TypeError: Cannot read property 'Symbol(requestOptions)' of undefined
    at Agent.removeSocket (_http_agent.js:444:20)
    at TLSSocket.onClose (_http_agent.js:371:11)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)

**Comment by gburgett** [comment] 2021-02-16 14:30
This is something that's happening inside the Contentful Management javascript SDK.  I'm tempted to rip that out and write my own client, as I've had issues with it before...

I tried upgrading the client but the issue still persists.  I'll keep this issue open for now until either it's fixed in contentful or I can come up with a better solution.

**Comment by jpowell** [comment] 2021-02-16 20:21
I've reproduced this issue, and this thread seems to be related: https://github.com/nodejs/node/issues/36364#issuecomment-741919783

i was able to use nvm to downgrade to node 12.17 locally to use the package for now

**Closed** 2021-04-06 13:20 UTC
